# syntax=docker/dockerfile:1
# Build stage
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Run stage
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/target/distributed-systems-hw4-1.0-SNAPSHOT.jar app.jar
EXPOSE 8080
CMD ["java", "-cp", "app.jar", "HW3.Server"]
