# syntax=docker/dockerfile:1
FROM maven:latest
WORKDIR /src
COPY pom.xml pom.xml
RUN mvn clean install
EXPOSE 8080
COPY src/main/java/HW3 ./src/main/java/HW3
CMD ["mvn", "compile", "exec:java", "-Dexec.mainClass=HW3.Server"]
